
class model_schema_constants:
  ATTRIBUTES = 'attributes'
  RELATIONSHIPS = 'relationships'
  METHODS = 'methods'
  INSTANCES = 'instances'
  FILTER = 'filter'
  COMPOSITE = 'composite'
  AND = 'and'
  OR = 'or'
  SORT = 'sort'
  PAGINATE = 'paginate'
  CREATE = 'create'
  DELETE = 'delete'
  ARGUMENTS = '_arguments'
  GET = '_get'
  SET = '_set'
  KEY = 'key'
  VALUE = 'value'
