
class model_schema_constants:
  ATTRIBUTES = 'attributes'
  RELATIONSHIPS = 'relationships'
  METHODS = 'methods'
  INSTANCES = 'instances'
  FILTER = 'filter'
  COMPOSITE = 'composite'
  AND = 'and'
  OR = 'or'
  SORT = 'sort'
  PAGINATE = 'paginate'
  CREATE = 'create'
  DELETE = 'delete'
  GET = 'get'
  SET = 'set'
  KEY = 'key'
  VALUE = 'value'
  REFERENCE_MODEL = 'Reference'
  REFERENCE = 'reference'
  COUNT = 'count'
  TEMPORARY_IDS = 'temporary_ids'
  ADD = 'add'
  REMOVE = 'remove'
  NULL = 'null'
  RUN = 'run'
