# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rowbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleinstance',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='rowbot.EventInstance'),
        ),
        migrations.AlterField(
            model_name='teaminstance',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='rowbot.EventInstance'),
        ),
    ]
