# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('row', '0002_auto_20171018_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
