# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('row', '0003_role_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='nickname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team',
        ),
    ]
