# Generated by Django 2.0.4 on 2018-07-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockmodel',
            name='under',
            field=models.ManyToManyField(related_name='over', to='base.MockModel'),
        ),
        migrations.AlterField(
            model_name='mockmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='mockparentmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
    ]
