# Generated by Django 2.0.4 on 2018-07-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MockModel',
        ),
    ]
