# Generated by Django 2.0.4 on 2018-07-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180715_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockmodel',
            name='parent',
        ),
        migrations.DeleteModel(
            name='MockModel',
        ),
        migrations.DeleteModel(
            name='MockParentModel',
        ),
    ]
