# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 08:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rowbot', '0002_auto_20171217_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventNotificationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('relative_duration', models.DurationField(default=datetime.timedelta(0))),
                ('is_negative', models.BooleanField(default=False)),
                ('is_absolute', models.BooleanField(default=False)),
                ('absolute_hour', models.IntegerField(default=0)),
                ('absolute_minute', models.DateTimeField(default=0)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_models', to='rowbot.EventModel')),
            ],
            options={
                'permissions': (),
            },
        ),
    ]
