# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowbot', '0003_eventnotificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventnotificationmodel',
            name='relative_duration',
            field=models.DurationField(),
        ),
    ]
