# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowbot', '0004_auto_20171219_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventnotificationmodel',
            name='absolute_minute',
            field=models.IntegerField(default=0),
        ),
    ]
