# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowbot', '0005_auto_20171219_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roleinstance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roleinstance',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
