# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowbot', '0006_auto_20171224_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='nickname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
